services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=movies_api_db'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/data/postgres'

volumes:
  pgdata:
